language: python
python:
  - "3.6"
os:
  - linux

install:
  - pip install -U pip setuptools
  - pip install -U -r requirements-ci.txt
script:
  - python -m flake8 ai/backend tests
  - python -m pytest --cov=ai.backend.kernel
after_success:
  - codecov

notifications:
  webhooks:
    secure: Gd9njovK7f0UBDDuwwwNUSIhaipvQQOjXWkPsNXZr04eO43PqElnOn2emjDEiXO78Ovu5GGyUk27fhmqy7JdYTHPVAAd98fVbmzFwPu3XKvDNSrylbrckqoKRejcN5rRsPSzMFOklhwC/NHKiBz+XD2OhfITAqrnSc5BXKnHgBfPxK5s662oj6pQl3Uvvp5RCsuU8ceHq7xg224Kdkx2If+0oyB/8xRqG4E6vCS55jnxGFCOjGkfNg1wP8v9c8a9R7KNtz4ErlxQ5hVzCE8l6pHUTvscehzu/7JJmxziKLuXJYOyUGOKJCaHcYPRoUiPo6N0WbW1snDHK0d6XNGz7BFS3DVfzBama6pB3h4uiM02k8I+lm13L2xXN0A9ger0pRvDEieUTnXEc/zEy9wPCkSbFKMSkbshEPHnFzvDNJIaQELIQ+zXmNdBSCki3848WKMh85REwRwxczHr+bgz8JILb5DSgDBSJu2G7mOWCM5dohDrH6UfLI6fG4Dl48dJpu8pEO86PxE7MJ/u+fgnEGjINaaudoM29TQ4ArXNLHcC2C40ONWh/nsmzktAz/WgVPSvLtyJGA4lSgRkzxSGNr8rG1OMM1jeE/kBu246P26di+AcYX3o1JjKQhI3U2ql9ht0npIRWxO31aWn1kY+GYyjPt9/QSBTwPY0PY0dkxQ=
