language: python
cache: pip
python:
  - "3.6"
os:
  - linux

install:
  - pip install -U pip setuptools
  - pip install -U -r requirements-ci.txt
script:
  - python -m flake8 ai/backend tests
  - python -m pytest -s --cov=ai.backend.kernel
after_success:
  - codecov

notifications:
  webhooks:
    - https://outlook.office.com/webhook/74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631@13c6a44d-9b52-4b9e-aa34-0513ee7131f2/TravisCI/f17430ff524f401e9e20dec933bf3bd1/f9fe633f-b557-4a72-9533-8a75ca534594
